apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etcd-shield
resources:
- ../../../config/
- certificate.yaml
configMapGenerator:
- files:
  - ./config.yaml
  name: etcd-shield-config
  behavior: replace

patches:
  - path: patch-imagepullpolicy.yaml
    target:
      kind: Deployment
      name: etcd-shield
  - path: patch-etcd-shield-metrics-tls.yaml
    target:
      kind: ServiceMonitor
      name: etcd-shield-metrics
  - path: patch-etcd-shield-prometheusrule.yaml
    target:
      kind: PrometheusRule
      name: etcd-shield-triggers
