apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd-shield-metrics
spec:
  endpoints:
    - interval: 15s
      scheme: https
      path: /metrics
      port: metrics
      authorization:
        credentials:
          key: token
          name: metrics-reader
      tlsConfig:
        insecureSkipVerify: true
