apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - ./config.yaml
  name: etcd-shield-config
# generatorOptions:
#   # until https://github.com/kubernetes-sigs/kustomize/issues/4475 is fixed
#   disableNameSuffixHash: true
images:
- name: etcd-shield
  newName: quay.io/ansadler/etcd-shield
  newTag: test
namespace: etcd-shield
resources:
- deployment.yaml
- ns.yaml
- rbac.yaml
- service.yaml
- webhook.yaml
- prometheus.etcd_shield_alerts.yaml
- ./metrics
