apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: etcd-shield-triggers
spec:
  groups:
  - name: etcd_shield_triggers
    interval: 1m
    rules:
    - alert: EtcdShieldDenyAdmission
      expr: etcd_shield_trigger != bool 0
      for: 2m
      keep_firing_for: 5m
      labels:
        severity: critical
      annotations:
        summary: etcd-shield is denying admission
        description: Etcd is nearing capacity limits, so etcd-shield is denying admission
    - record: etcd_shield_trigger
      expr: |
        (((max(etcd_mvcc_db_total_size_in_bytes) >= bool (8589934592 * 0.95)) == 1) or
            (((max(etcd_mvcc_db_total_size_in_bytes) >= bool (8589934592 * 0.8)) == 1) and
            ((count without (alertname, alertstate, severity)
            (ALERTS{
              alertname="EtcdShieldDenyAdmission",
              alertstate="firing",
              severity="critical"
            }) == bool 1) != 0)))
